global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "fastapi"
    static_configs:
      - targets: ["fastapi:8000"]
  - job_name: "celery-worker"
    static_configs:
      - targets: ["celery-worker:5555"]
  - job_name: "flower"
    static_configs:
      - targets: ["flower:5555"]
  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]
  - job_name: "postgres"
    static_configs:
      - targets: ["postgres:5432"]
