name: Deploy to GCP MIG

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. 코드 체크아웃
    - name: Checkout code
      uses: actions/checkout@v3
      
    # 2. GCP 인증
    - name: Google Auth
      id: auth
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    # 3. Docker 설정
    - name: Docker configuration
      run: |-
        gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev

    # 4. Docker 이미지 빌드 및 푸시 
    - name: Build and Push Container
      run: |-
        docker build -t ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.ARTIFACT_REPO }}/${{ secrets.IMAGE_NAME }}:latest .
        docker push ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.ARTIFACT_REPO }}/${{ secrets.IMAGE_NAME }}:latest


    # 배포 전 최대 크기 임시 증가
    - name: Increase Max Size
      run: |-
        gcloud compute instance-groups managed set-autoscaling ${{ secrets.MIG_NAME }} \
         --region=${{ secrets.GCP_REGION }} \
         --max-num-replicas=8

    # 블루그린  업데이트
    - name: bluegreen Update MIG
      run: |-
       gcloud compute instance-groups managed rolling-action replace ${{ secrets.MIG_NAME }} \
         --region=${{ secrets.GCP_REGION }} \
         --max-surge=3 \
         --max-unavailable=0

   # 배포 후 최대 크기 원복
    - name: Restore Max Size
      run: |-
       gcloud compute instance-groups managed set-autoscaling ${{ secrets.MIG_NAME }} \
         --region=${{ secrets.GCP_REGION }} \
         --max-num-replicas=5
